engines:
  eslint:
    enabled: true
    channel: eslint-3
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME

ratings:
   paths:
     - index.js

exclude_paths:
  - "*.md"
  - LICENSE
  - package.json
  - spec.js
  - yarn.lock
